### ISSUE TITLE
Add the (George) Box law

### ISSUE THREAD

**Issue by mo-gr** [dwmkerr/hacker-laws#263]
It goes something like this: "All models are wrong, but some are useful" (source https://en.wikipedia.org/wiki/All_models_are_wrong)

It is a variation of "All abstractions are leaky", but it is different enough to be mentioned explicitly, imho

**Comment by puremana** [comment]
My only issue with this is it seems to apply specifically in regard to statistics, not development

**Comment by dwmkerr** [comment]
I'm inclined to think this could work for development. On the wikipedia page they use maps as an example- a map is not a perfect model of a city, it might even have mistakes, it doesn't have all the data, but is still use.

An APM tool could be a good example - it might show machines as individual hosts, but in reality they might be virtual machines on a rack, it's an abstraction, and an incomplete one, but still useful.

Still, happy to leave this open for a bit to see if anyone else has any thoughts!

**Comment by igbanam** [comment]
I don't know much about the law — and haven't researched it since I'm browsing through issues here — but in my opinion, I think this also pertains to development. 

From forming teams… we have a model of team integration which always changes. Our original model was wrong, but it sure was useful.

Through building the software… requirements engineering is still not a deterministic science. My grounds for this claim is that requirements themselves change with time. So any model we use to shape our software is inherently wrong as time passes. "Any" can roll up to "All", hence the law.

I may just have blabbed rubbish… but these are my thoughts

**Comment by dwmkerr** [comment]
Not rubbish @igbanam, I agree, think this is a useful law here!

**Comment by puremana** [comment]
I stand corrected I guess 😀

**Comment by dwmkerr** [comment]
lol @puremana your profile picture fits that statement really well! OK I think I'll add this to the list when I get some time soon!

**Comment by mo-gr** [comment]
Really great to see such a thoughtful and on-topic discussion about this. Thanks everyone for being so awesome!

**Comment by dwmkerr** [comment]
@mo-gr there's so much unpleasant stuff on the internet, it's always great to see thoughtful and constructive discussions! 😄

**Comment by dwmkerr** [comment]
FYI this is the next one on the list to do I think, it's generated a good discussion and I see it all the time the more I think about it!
