### ISSUE TITLE
Tranlate to vietnamese language

### ISSUE THREAD

**Issue by truonghoangnguyen** [dwmkerr/hacker-laws#364]
Hi
I have completed the translation into Vietnamese here: https://github.com/truonghoangnguyen/hacker-laws/tree/main/vi . 

The next step if you need anything more please let me know.

**Comment by dwmkerr** [comment]
Hi @truonghoangnguyen that's awesome! To add to the list of translations, please sign into Git Localise: https://gitlocalize.com/

Once you have signed in, let me know and I will make you the moderator for Vietnamese. Then open a pull request that adds the link to the 'translations' section at the top of the README and bottom (I can add that if you prefer) and put the translation in the [./translations](./translations) folder. You can also add a link to your 'Sponsors' page if you like in the [Translations](https://github.com/dwmkerr/hacker-laws#translations) - you might get some support from people.

Thanks so much for your effort here! Once it's integrated I'll post on social media and link to you 😄

**Comment by truonghoangnguyen** [comment]
Hi, @dwmkerr I'm logged in to Git Localise (link here: https://gitlocalize.com/repo/6953/vi)

Have good day

**Comment by dwmkerr** [comment]
Excellent, I've made you the moderator for Vietnamese, you should be able
to create a PR into the main repo now!

**Comment by truonghoangnguyen** [comment]
Hi @dwmkerr .
I have finished translating to Vietnamese on gitlocalize and create review request.
https://gitlocalize.com/repo/2513/vi 

The next step if you need please let me know.

**Comment by dwmkerr** [comment]
This is awesome, thank-you! BTW I think you need to hit the 'send pull
request' button for it to open a PR into the main repo, once that's done
I'll merge and share!

**Comment by truonghoangnguyen** [comment]
Hi
I got an error while creating PR, not sure if it's temporary or permanent, but I think it's best to let you know the situation.

![image](https://user-images.githubusercontent.com/1657877/149070306-5463f6e6-426f-42d0-b6fe-d3959f17df2d.png)

**Comment by dwmkerr** [comment]
That's really odd - for now maybe you can manually just PR the translation file into the repo?

**Comment by truonghoangnguyen** [comment]
Hi
I don't know how to do it, can you guide me or give me online documents ?

Thank you

**Comment by dwmkerr** [comment]
Sure thing:

1. First, update your repository so that the translated file is in the location `translations\vn.md`.
2. Open a pull request that requests that the `vn.md` file is merged into this repository
3. In the pull request if you can update the table below with your details, that's great, if not I can do it (I just need to know how to write Vietnamese (as in the language) in Vietnamese properly, so that the table is correct!)

![image](https://user-images.githubusercontent.com/1926984/149610558-5c0e6802-1eca-41e9-9ba8-30cdd0a4a00c.png)

As long as the translation files are in this folder it should work:

![image](https://user-images.githubusercontent.com/1926984/149610594-76c97ab0-4bcb-4089-983e-87c8944d497e.png)

If I manually merge the file then the commit will be in my name which means you won't be properly listed as contributor on GitHub and it's nice if you are shown in the contributors section!
